"use client";

import { useEffect, useState } from "react";

type Notice = { id: string; type: string; title: string; body: string; href: string; read_at: string | null; created_at: string };
type Inbox = { notifications: Notice[]; unread: number; preferences: { collaborationEnabled: boolean; weeklyEnabled: boolean }; queue: Array<{ status: string; count: number }> };

export function NotificationInbox() {
  const [inbox, setInbox] = useState<Inbox | null>(null); const [message, setMessage] = useState(""); const [filter, setFilter] = useState<"all" | "unread">("all");
  const load = () => fetch("/api/notifications").then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setInbox(data); }).catch((error) => setMessage(error instanceof Error ? error.message : "Inbox unavailable"));
  useEffect(() => { void load(); }, []);
  const patch = async (body: Record<string, unknown>) => { const response = await fetch("/api/notifications", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) { setMessage("Update failed."); return false; } return true; };
  const markRead = async (notice: Notice) => { if (notice.read_at || !(await patch({ action: "read", id: notice.id }))) return; const now = new Date().toISOString(); setInbox((current) => current ? { ...current, unread: Math.max(0, current.unread - 1), notifications: current.notifications.map((item) => item.id === notice.id ? { ...item, read_at: now } : item) } : current); };
  const markAll = async () => { if (!(await patch({ action: "read_all" }))) return; const now = new Date().toISOString(); setInbox((current) => current ? { ...current, unread: 0, notifications: current.notifications.map((item) => ({ ...item, read_at: item.read_at ?? now })) } : current); };
  const preferences = async (changes: Partial<Inbox["preferences"]>) => { if (!inbox) return; const next = { ...inbox.preferences, ...changes }; setInbox({ ...inbox, preferences: next }); if (!(await patch({ action: "preferences", ...next }))) setInbox({ ...inbox }); else setMessage("Preferences saved."); };
  const remove = async (notice: Notice) => { const response = await fetch(`/api/notifications?id=${encodeURIComponent(notice.id)}`, { method: "DELETE" }); if (!response.ok) return; setInbox((current) => current ? { ...current, unread: current.unread - Number(!notice.read_at), notifications: current.notifications.filter((item) => item.id !== notice.id) } : current); };
  if (!inbox) return <section className="inbox-loading shell" aria-live="polite">{message || "Loading your decision inbox…"}</section>;
  const visible = inbox.notifications.filter((item) => filter === "all" || !item.read_at); const pending = inbox.queue.find((item) => item.status === "pending")?.count ?? 0;
  return <section className="notification-inbox shell"><div className="inbox-toolbar"><div><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>ALL</button><button className={filter === "unread" ? "active" : ""} onClick={() => setFilter("unread")}>UNREAD · {inbox.unread}</button></div><span role="status">{message}</span><button onClick={markAll} disabled={!inbox.unread}>MARK ALL READ</button></div>
    <div className="inbox-layout"><div className="notice-list">{visible.length ? visible.map((notice) => <article className={notice.read_at ? "" : "unread"} key={notice.id}><i /><div><span>{notice.type.replaceAll("_", " ")}</span><h2>{notice.title}</h2><p>{notice.body}</p><small>{new Date(notice.created_at).toLocaleString()}</small></div><div><a href={notice.href} onClick={() => markRead(notice)}>OPEN ↗</a>{!notice.read_at ? <button onClick={() => markRead(notice)} aria-label={`Mark ${notice.title} as read`}>✓</button> : null}<button onClick={() => remove(notice)} aria-label={`Delete ${notice.title}`}>×</button></div></article>) : <div className="inbox-empty"><strong>You’re caught up.</strong><p>New collaboration activity and weekly briefings will appear here.</p></div>}</div>
      <aside className="notification-settings"><span className="section-index">DELIVERY SETTINGS</span><h2>What reaches you.</h2><label><span><strong>Collaboration</strong><small>Invites, comments, edits, and access changes</small></span><input type="checkbox" checked={inbox.preferences.collaborationEnabled} onChange={(event) => preferences({ collaborationEnabled: event.target.checked })} /></label><label><span><strong>Weekly briefing</strong><small>Fixtures, model record, and scouting activity</small></span><input type="checkbox" checked={inbox.preferences.weeklyEnabled} onChange={(event) => preferences({ weeklyEnabled: event.target.checked })} /></label><div className="queue-health"><i /><span><strong>DELIVERY HEALTHY</strong><small>{pending} pending · retries use bounded exponential backoff</small></span></div><p>Email is an optional future channel. The in-app inbox is authoritative and does not depend on an external provider.</p></aside></div>
  </section>;
}
