"use client";

import { useState } from "react";
import { journeyId } from "../product-events";

const tasks = [{ title: "Compare two players", detail: "Open Trends, add a third player, and explain which trajectory looks most reliable.", href: "/trends" }, { title: "Build a transfer case", detail: "Choose a reference player, compare replacements, and identify the best value option.", href: "/transfers" }, { title: "Plan a squad change", detail: "Change one starter while keeping the squad inside its budget.", href: "/squad-planner" }];
export function FeedbackForm() {
  const [category, setCategory] = useState("usability"); const [rating, setRating] = useState(4); const [message, setMessage] = useState(""); const [status, setStatus] = useState(""); const [sending, setSending] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSending(true); setStatus(""); try { const response = await fetch("/api/feedback", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ journeyId: journeyId(), category, rating, message, sourcePath: window.location.pathname }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage(""); setStatus("Thank you—your feedback is now part of the product evidence."); } catch (error) { setStatus(error instanceof Error ? error.message : "Feedback could not be saved."); } finally { setSending(false); } };
  return <section className="feedback-shell shell"><div className="beta-tasks"><div className="section-index">01 / TEST A REAL FLOW</div>{tasks.map((task, index) => <article key={task.title}><span>0{index + 1}</span><div><h2>{task.title}</h2><p>{task.detail}</p></div><a href={task.href}>Start task →</a></article>)}</div><form className="feedback-form" onSubmit={submit}><div className="section-index">02 / REPORT THE EXPERIENCE</div><label><span>What kind of feedback?</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="usability">Usability</option><option value="accuracy">Model clarity or accuracy</option><option value="accessibility">Accessibility</option><option value="bug">Bug</option><option value="idea">Feature idea</option></select></label><fieldset><legend>How useful was Touchline?</legend>{[1,2,3,4,5].map((value) => <label key={value}><input type="radio" name="rating" value={value} checked={rating === value} onChange={() => setRating(value)} /><span>{value}</span></label>)}</fieldset><label><span>What happened?</span><textarea required minLength={10} maxLength={1200} value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Describe the task, what you expected, and where you hesitated." /></label><button disabled={sending}>{sending ? "SAVING…" : "SUBMIT ANONYMOUS FEEDBACK"}</button>{status ? <p role="status">{status}</p> : null}</form></section>;
}
