"use client";

import { useEffect, useState } from "react";

type Row = Record<string, string | number | null>;
type Operations = { generatedAt: string; admin: string; database: { status: string }; retention: Record<string, number>; summary: { requests: number; errors: number; average_latency_ms: number }; routes: Row[]; errors: Row[]; security: Row[]; rateLimits: { active_windows: number; repeated_requests: number; busiest_window: number }; syncRuns: Row[]; alerts: Row[]; deadLetters: Row[]; records: Record<string, number> };

export function OperationsDashboard() {
  const [data, setData] = useState<Operations | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/operations").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Operations unavailable")); }, []);
  if (error) return <section className="ops-denied shell"><strong>ACCESS RESTRICTED</strong><h2>{error}</h2><p>This console is limited to the configured Touchline operator account.</p></section>;
  if (!data) return <section className="ops-denied shell" aria-live="polite">Loading production operations…</section>;
  const errorRate = data.summary.requests ? data.summary.errors / data.summary.requests : 0;
  return <div className="operations-dashboard shell">
    <section className="ops-kpis"><article><span>24H REQUESTS</span><strong>{data.summary.requests ?? 0}</strong><small>{data.summary.average_latency_ms ?? 0} ms average</small></article><article><span>ERROR RATE</span><strong>{(errorRate * 100).toFixed(2)}%</strong><small>{data.summary.errors ?? 0} responses ≥ 400</small></article><article><span>RATE WINDOWS</span><strong>{data.rateLimits.active_windows ?? 0}</strong><small>Peak {data.rateLimits.busiest_window ?? 0} req/min</small></article><article><span>DATABASE</span><strong>{data.database.status}</strong><small>{Object.values(data.records).reduce((sum, value) => sum + value, 0)} product records</small></article></section>
    <section className="ops-grid"><div className="ops-panel wide"><span className="section-index">01 / ROUTES</span><h2>Traffic and latency</h2><div className="ops-table"><div><b>ROUTE</b><b>REQUESTS</b><b>ERRORS</b><b>AVG / MAX</b></div>{data.routes.map((row) => <div key={String(row.route)}><code>{row.route}</code><strong>{row.requests}</strong><strong>{row.errors}</strong><span>{row.average_latency_ms} / {row.max_latency_ms} ms</span></div>)}</div></div>
      <div className="ops-panel"><span className="section-index">02 / ALERTS</span><h2>Automatic signals</h2>{data.alerts.map((row) => <article className="ops-event" key={String(row.id)}><i className={String(row.severity)} /><div><strong>{row.title}</strong><p>{row.detail}</p><small>{new Date(String(row.created_at)).toLocaleString()}</small></div></article>)}{data.deadLetters.map((row) => <article className="ops-event" key={`dead:${row.id}`}><i className="critical" /><div><strong>Notification dead letter · {row.type}</strong><p>{row.error}</p><small>{row.attempts} attempts · {new Date(String(row.created_at)).toLocaleString()}</small></div></article>)}{!data.alerts.length && !data.deadLetters.length ? <p className="ops-clear">No operational alerts or dead letters.</p> : null}</div>
      <div className="ops-panel"><span className="section-index">03 / ERRORS</span><h2>Application failures</h2>{data.errors.length ? data.errors.map((row) => <article className="ops-event" key={`${row.fingerprint}:${row.route}`}><i className="error" /><div><strong>{row.route} · {row.fingerprint}</strong><p>{row.message}</p><small>{row.occurrences} occurrence(s) · last {new Date(String(row.last_seen)).toLocaleString()}</small></div></article>) : <p className="ops-clear">No captured failures in seven days.</p>}</div>
      <div className="ops-panel"><span className="section-index">04 / SECURITY</span><h2>Rejected requests</h2>{data.security.length ? data.security.map((row) => <article className="ops-event" key={`${row.category}:${row.route}:${row.status}`}><i className="warn" /><div><strong>{String(row.category).replaceAll("_", " ")}</strong><p>{row.route} · HTTP {row.status}</p><small>{row.occurrences} occurrence(s) · last {new Date(String(row.last_seen)).toLocaleString()}</small></div></article>) : <p className="ops-clear">No security denials in seven days.</p>}</div>
      <div className="ops-panel"><span className="section-index">05 / AUTOMATION</span><h2>Provider lifecycle</h2>{data.syncRuns.map((row) => <article className="ops-event" key={String(row.id)}><i className={row.status === "success" ? "ok" : "error"} /><div><strong>{row.source} · {row.trigger}</strong><p>{row.status} in {row.duration_ms} ms</p><small>{new Date(String(row.completed_at)).toLocaleString()}</small></div></article>)}</div>
      <div className="ops-panel retention"><span className="section-index">06 / PRIVACY</span><h2>Bounded retention</h2><p>Identifiers used for limits are one-way hashed with a rotating daily scope. Raw IP addresses, names, and request payloads are never stored.</p><div>{Object.entries(data.retention).map(([name, value]) => <span key={name}><b>{value}</b>{name.replaceAll(/([A-Z])/g, " $1")}</span>)}</div></div>
    </section><p className="ops-generated">Generated {new Date(data.generatedAt).toLocaleString()} · signed in as {data.admin}</p>
  </div>;
}
