"use client";

import { useEffect, useMemo, useState } from "react";

type Plan = { id: string; owner_id: string; access_role: "owner" | "editor" | "viewer"; kind: "squad" | "transfer"; name: string; description: string; payload: { url: string; summary?: Record<string, string | number | number[]> }; visibility: "private" | "public"; public_slug: string | null; archived: boolean; version: number; version_count: number; created_at: string; updated_at: string };
type Version = { id: number; version: number; name: string; description: string; payload: Plan["payload"]; created_at: string };
type Member = { id: string; email: string; role: "editor" | "viewer"; user_id: string | null; created_at: string };
type Comment = { id: string; author_email: string; body: string; player_id: number | null; created_at: string };
type Event = { id: number; actor_email: string; action: string; detail: string; created_at: string };
type Collaboration = { role: Plan["access_role"]; members: Member[]; comments: Comment[]; activity: Event[] };

export function WorkspaceDashboard() {
  const [plans, setPlans] = useState<Plan[]>([]);
  const [filter, setFilter] = useState<"active" | "archived" | "all">("active");
  const [selected, setSelected] = useState<string | null>(null);
  const [versions, setVersions] = useState<Version[]>([]);
  const [collaboration, setCollaboration] = useState<Collaboration | null>(null);
  const [inviteEmail, setInviteEmail] = useState("");
  const [inviteRole, setInviteRole] = useState<"editor" | "viewer">("editor");
  const [comment, setComment] = useState("");
  const [commentPlayer, setCommentPlayer] = useState("");
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");

  const load = () => fetch("/api/workspace/plans?archived=all").then(async (response) => {
    const data = await response.json(); if (!response.ok) throw new Error(data.error); setPlans(data.plans);
  }).catch((error) => setMessage(error instanceof Error ? error.message : "Workspace unavailable")).finally(() => setLoading(false));
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => plans.filter((plan) => filter === "all" || plan.archived === (filter === "archived")), [filter, plans]);

  const update = async (plan: Plan, changes: Partial<Pick<Plan, "name" | "description" | "visibility" | "archived">> & { payload?: Plan["payload"] }) => {
    const previous = plans; const optimistic = { ...plan, ...changes, version: plan.version + 1, updated_at: new Date().toISOString() }; setPlans((items) => items.map((item) => item.id === plan.id ? optimistic : item)); setMessage("Saving…");
    try { const response = await fetch(`/api/workspace/plans/${plan.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...changes, expectedVersion: plan.version }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setPlans((items) => items.map((item) => item.id === plan.id ? { ...data.plan, access_role: plan.access_role, owner_id: plan.owner_id } : item)); setMessage("Saved to the room."); }
    catch (error) { setPlans(previous); setMessage(error instanceof Error ? `${error.message} Your previous state was restored.` : "Save failed. Your previous state was restored."); }
  };
  const remove = async (plan: Plan) => { const previous = plans; setPlans((items) => items.filter((item) => item.id !== plan.id)); try { const response = await fetch(`/api/workspace/plans/${plan.id}`, { method: "DELETE" }); if (!response.ok) throw new Error(); setMessage("Plan deleted."); } catch { setPlans(previous); setMessage("Delete failed. The plan was restored."); } };
  const duplicate = async (plan: Plan) => { setMessage("Duplicating…"); try { const response = await fetch("/api/workspace/plans", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind: plan.kind, name: `${plan.name} copy`, description: plan.description, payload: plan.payload }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setPlans((items) => [data.plan, ...items]); setMessage("Private copy created."); } catch { setMessage("The plan could not be duplicated."); } };
  const showHistory = async (plan: Plan) => { if (selected === `history:${plan.id}`) { setSelected(null); return; } const response = await fetch(`/api/workspace/plans/${plan.id}`); const data = await response.json(); if (response.ok) { setSelected(`history:${plan.id}`); setVersions(data.versions); } };
  const showRoom = async (plan: Plan) => { if (selected === `room:${plan.id}`) { setSelected(null); return; } const response = await fetch(`/api/workspace/plans/${plan.id}/collaboration`); const data = await response.json(); if (response.ok) { setSelected(`room:${plan.id}`); setCollaboration(data); } };
  const restore = (plan: Plan, version: Version) => update(plan, { name: version.name, description: version.description, payload: version.payload });
  const invite = async (plan: Plan) => { const response = await fetch(`/api/workspace/plans/${plan.id}/collaboration`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "invite", invite: { email: inviteEmail, role: inviteRole } }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error); return; } setCollaboration((current) => current ? { ...current, members: [...current.members.filter((member) => member.id !== data.member.id), data.member] } : current); setInviteEmail(""); setMessage("Invitation access is ready. Share the workspace URL with that person."); };
  const postComment = async (plan: Plan) => { const response = await fetch(`/api/workspace/plans/${plan.id}/collaboration`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "comment", comment: { body: comment, playerId: commentPlayer ? Number(commentPlayer) : null } }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error); return; } setCollaboration((current) => current ? { ...current, comments: [data.comment, ...current.comments] } : current); setComment(""); setCommentPlayer(""); setMessage("Comment added."); };
  const revoke = async (plan: Plan, member: Member) => { const response = await fetch(`/api/workspace/plans/${plan.id}/collaboration?member=${encodeURIComponent(member.id)}`, { method: "DELETE" }); if (!response.ok) { setMessage("Access could not be revoked."); return; } setCollaboration((current) => current ? { ...current, members: current.members.filter((item) => item.id !== member.id) } : current); setMessage(`${member.email} no longer has access.`); };

  if (loading) return <section className="workspace-loading shell">Loading your private workspace…</section>;
  return <section className="workspace-dashboard shell">
    <div className="workspace-toolbar"><div><button className={filter === "active" ? "active" : ""} onClick={() => setFilter("active")}>ACTIVE</button><button className={filter === "archived" ? "active" : ""} onClick={() => setFilter("archived")}>ARCHIVED</button><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>ALL</button></div><span role="status">{message}</span><a href="/squad-planner">NEW SQUAD PLAN ↗</a><a href="/transfers">NEW TRANSFER SCENARIO ↗</a></div>
    {visible.length ? <div className="workspace-list">{visible.map((plan) => <article key={plan.id} className="workspace-card">
      <div className="workspace-card-top"><span className={`plan-kind ${plan.kind}`}>{plan.kind}</span><span>{plan.access_role.toUpperCase()}</span><span>{plan.visibility === "private" ? "PRIVATE" : "READ-ONLY LINK ACTIVE"}</span><span>v{plan.version}</span></div>
      <input aria-label={`Name for ${plan.name}`} disabled={plan.access_role === "viewer"} value={plan.name} onChange={(event) => setPlans((items) => items.map((item) => item.id === plan.id ? { ...item, name: event.target.value } : item))} onBlur={(event) => { if (event.target.value.trim()) void update(plan, { name: event.target.value.trim() }); }} />
      <textarea aria-label={`Description for ${plan.name}`} disabled={plan.access_role === "viewer"} value={plan.description} placeholder="Add decision notes…" onChange={(event) => setPlans((items) => items.map((item) => item.id === plan.id ? { ...item, description: event.target.value } : item))} onBlur={(event) => { void update(plan, { description: event.target.value }); }} />
      <p>Updated {new Date(plan.updated_at).toLocaleString()} · {plan.version_count} saved versions</p>
      <div className="workspace-actions"><a href={plan.payload.url}>OPEN</a><button onClick={() => showRoom(plan)}>ROOM</button>{plan.visibility === "public" && plan.public_slug ? <a href={`/shared/${plan.public_slug}`}>VIEW SHARED</a> : null}{plan.access_role === "owner" ? <><button onClick={() => update(plan, { visibility: plan.visibility === "private" ? "public" : "private" })}>{plan.visibility === "private" ? "CREATE READ-ONLY LINK" : "MAKE PRIVATE"}</button><button onClick={() => update(plan, { archived: !plan.archived })}>{plan.archived ? "RESTORE" : "ARCHIVE"}</button><button className="danger" onClick={() => remove(plan)}>DELETE</button></> : null}<button onClick={() => duplicate(plan)}>DUPLICATE</button><button onClick={() => showHistory(plan)}>HISTORY</button></div>
      {selected === `history:${plan.id}` ? <div className="version-history"><strong>VERSION HISTORY</strong>{versions.map((version) => <div key={version.id}><span>v{version.version} · {new Date(version.created_at).toLocaleString()}</span><b>{version.name}</b><button disabled={version.version === plan.version || plan.access_role === "viewer"} onClick={() => restore(plan, version)}>{version.version === plan.version ? "CURRENT" : "RESTORE"}</button></div>)}</div> : null}
      {selected === `room:${plan.id}` && collaboration ? <div className="collaboration-room">
        <div className="room-head"><div><span>COLLABORATIVE SCOUTING ROOM</span><h3>Decide together, with accountability.</h3></div><strong>{collaboration.members.length + 1} PEOPLE</strong></div>
        <div className="room-grid"><section><h4>ACCESS</h4><div className="member-row"><span><b>You</b><small>{collaboration.role}</small></span><em>ACTIVE</em></div>{collaboration.members.map((member) => <div className="member-row" key={member.id}><span><b>{member.email}</b><small>{member.role} · {member.user_id ? "joined" : "invited"}</small></span>{collaboration.role === "owner" ? <button onClick={() => revoke(plan, member)}>REVOKE</button> : null}</div>)}{collaboration.role === "owner" ? <div className="invite-controls"><input type="email" placeholder="teammate@example.com" aria-label="Collaborator email" value={inviteEmail} onChange={(event) => setInviteEmail(event.target.value)} /><select aria-label="Collaborator role" value={inviteRole} onChange={(event) => setInviteRole(event.target.value as "editor" | "viewer")}><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button disabled={!inviteEmail} onClick={() => invite(plan)}>GRANT ACCESS</button></div> : null}</section>
        <section><h4>COMMENTS</h4><div className="comment-controls"><input inputMode="numeric" placeholder="Player ID (optional)" aria-label="Player ID for comment" value={commentPlayer} onChange={(event) => setCommentPlayer(event.target.value.replace(/\D/g, ""))} /><textarea placeholder="Add a scouting note or decision rationale…" aria-label="New room comment" value={comment} onChange={(event) => setComment(event.target.value)} /><button disabled={!comment.trim()} onClick={() => postComment(plan)}>POST COMMENT</button></div><div className="comment-list">{collaboration.comments.map((item) => <article key={item.id}><b>{item.author_email}</b>{item.player_id ? <a href={`/players/${item.player_id}`}>PLAYER #{item.player_id} ↗</a> : null}<p>{item.body}</p><small>{new Date(item.created_at).toLocaleString()}</small></article>)}</div></section>
        <section><h4>ACTIVITY</h4><div className="activity-list">{collaboration.activity.map((item) => <article key={item.id}><i /><div><b>{item.action.replaceAll("_", " ")}</b><p>{item.detail}</p><small>{item.actor_email} · {new Date(item.created_at).toLocaleString()}</small></div></article>)}</div></section></div>
      </div> : null}
    </article>)}</div> : <div className="workspace-empty"><strong>No {filter === "all" ? "" : filter} plans yet.</strong><p>Save a Squad Planner or Transfer Builder scenario to start your private decision history.</p></div>}
  </section>;
}
