"use client";

import { useEffect, useMemo, useState } from "react";

type Plan = { id: string; kind: "squad" | "transfer"; name: string; description: string; payload: { url: string; summary?: Record<string, string | number | number[]> }; visibility: "private" | "public"; public_slug: string | null; archived: boolean; version: number; version_count: number; created_at: string; updated_at: string };
type Version = { id: number; version: number; name: string; description: string; payload: Plan["payload"]; created_at: string };

export function WorkspaceDashboard() {
  const [plans, setPlans] = useState<Plan[]>([]); const [filter, setFilter] = useState<"active" | "archived" | "all">("active"); const [selected, setSelected] = useState<string | null>(null); const [versions, setVersions] = useState<Version[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const load = () => fetch("/api/workspace/plans?archived=all").then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setPlans(data.plans); }).catch((error) => setMessage(error instanceof Error ? error.message : "Workspace unavailable")).finally(() => setLoading(false));
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => plans.filter((plan) => filter === "all" || plan.archived === (filter === "archived")), [filter, plans]);
  const update = async (plan: Plan, changes: Partial<Pick<Plan, "name" | "description" | "visibility" | "archived">> & { payload?: Plan["payload"] }) => {
    const previous = plans; const optimistic = { ...plan, ...changes, version: plan.version + 1, updated_at: new Date().toISOString() }; setPlans((items) => items.map((item) => item.id === plan.id ? optimistic : item)); setMessage("Saving…");
    try { const response = await fetch(`/api/workspace/plans/${plan.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...changes, expectedVersion: plan.version }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setPlans((items) => items.map((item) => item.id === plan.id ? data.plan : item)); setMessage("Saved to your workspace."); }
    catch (error) { setPlans(previous); setMessage(error instanceof Error ? `${error.message} Your previous state was restored.` : "Save failed. Your previous state was restored."); }
  };
  const remove = async (plan: Plan) => { const previous = plans; setPlans((items) => items.filter((item) => item.id !== plan.id)); try { const response = await fetch(`/api/workspace/plans/${plan.id}`, { method: "DELETE" }); if (!response.ok) throw new Error(); setMessage("Plan deleted."); } catch { setPlans(previous); setMessage("Delete failed. The plan was restored."); } };
  const duplicate = async (plan: Plan) => { setMessage("Duplicating…"); try { const response = await fetch("/api/workspace/plans", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind: plan.kind, name: `${plan.name} copy`, description: plan.description, payload: plan.payload }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setPlans((items) => [data.plan, ...items]); setMessage("Private copy created."); } catch { setMessage("The plan could not be duplicated."); } };
  const showHistory = async (plan: Plan) => { if (selected === plan.id) { setSelected(null); return; } const response = await fetch(`/api/workspace/plans/${plan.id}`); const data = await response.json(); if (response.ok) { setSelected(plan.id); setVersions(data.versions); } };
  const restore = (plan: Plan, version: Version) => update(plan, { name: version.name, description: version.description, payload: version.payload });
  if (loading) return <section className="workspace-loading shell">Loading your private workspace…</section>;
  return <section className="workspace-dashboard shell"><div className="workspace-toolbar"><div><button className={filter === "active" ? "active" : ""} onClick={() => setFilter("active")}>ACTIVE</button><button className={filter === "archived" ? "active" : ""} onClick={() => setFilter("archived")}>ARCHIVED</button><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>ALL</button></div><span role="status">{message}</span><a href="/squad-planner">NEW SQUAD PLAN ↗</a><a href="/transfers">NEW TRANSFER SCENARIO ↗</a></div>{visible.length ? <div className="workspace-list">{visible.map((plan) => <article key={plan.id} className="workspace-card"><div className="workspace-card-top"><span className={`plan-kind ${plan.kind}`}>{plan.kind}</span><span>{plan.visibility === "private" ? "PRIVATE" : "READ-ONLY LINK ACTIVE"}</span><span>v{plan.version}</span></div><input aria-label={`Name for ${plan.name}`} value={plan.name} onChange={(event) => setPlans((items) => items.map((item) => item.id === plan.id ? { ...item, name: event.target.value } : item))} onBlur={(event) => { if (event.target.value.trim()) void update(plan, { name: event.target.value.trim() }); }} /><textarea aria-label={`Description for ${plan.name}`} value={plan.description} placeholder="Add decision notes…" onChange={(event) => setPlans((items) => items.map((item) => item.id === plan.id ? { ...item, description: event.target.value } : item))} onBlur={(event) => { void update(plan, { description: event.target.value }); }} /><p>Updated {new Date(plan.updated_at).toLocaleString()} · {plan.version_count} saved versions</p><div className="workspace-actions"><a href={plan.payload.url}>OPEN</a>{plan.visibility === "public" && plan.public_slug ? <a href={`/shared/${plan.public_slug}`}>VIEW SHARED</a> : null}<button onClick={() => update(plan, { visibility: plan.visibility === "private" ? "public" : "private" })}>{plan.visibility === "private" ? "CREATE READ-ONLY LINK" : "MAKE PRIVATE"}</button><button onClick={() => duplicate(plan)}>DUPLICATE</button><button onClick={() => update(plan, { archived: !plan.archived })}>{plan.archived ? "RESTORE" : "ARCHIVE"}</button><button onClick={() => showHistory(plan)}>HISTORY</button><button className="danger" onClick={() => remove(plan)}>DELETE</button></div>{selected === plan.id ? <div className="version-history"><strong>VERSION HISTORY</strong>{versions.map((version) => <div key={version.id}><span>v{version.version} · {new Date(version.created_at).toLocaleString()}</span><b>{version.name}</b><button disabled={version.version === plan.version} onClick={() => restore(plan, version)}>{version.version === plan.version ? "CURRENT" : "RESTORE"}</button></div>)}</div> : null}</article>)}</div> : <div className="workspace-empty"><strong>No {filter === "all" ? "" : filter} plans yet.</strong><p>Save a Squad Planner or Transfer Builder scenario to start your private decision history.</p></div>}</section>;
}
